### ISSUE TITLE
Allow specific image file.

### ISSUE THREAD

**Issue by BrianPugh** [wokwi/rp2040js#114]
Would you be interested in having the micropython image be specifiable via CLI args for the `start:micropython` script? I'm not a javascript/typescript dev, but if you're open to the idea, I think I could try and make a PR. Seems like something like `minimist` is the way to go for argument parsing?

**Comment by urish** [comment]
Sounds like a useful option. What is your specific use case for this? What are you working on?

**Comment by BrianPugh** [comment]
I'm using rp2040js as an integration tester for [Belay](https://github.com/BrianPugh/belay). I would like to swap between 2 images (micropython and circuitpython), so having the image be a CLI option seems like a natural choice.

**Comment by urish** [comment]
Cool use case, thanks for explaining!

**Comment by mingpepe** [comment]
This feature also useful for me.

**Comment by BrianPugh** [comment]
resolved in #116
