### ISSUE TITLE
SSD1306 broken on micropython 1.20+

### ISSUE THREAD

**Issue by treysis** [wokwi/rp2040js#135]
Trying to interface the board-ssd1306 component via I2C gives the following error:

![image](https://github.com/wokwi/rp2040js/assets/26790192/7281f46c-d184-46cc-a42e-1bf4fbeff20e)

Setting micropython environment in `diagram.json` to below 1.20 works, e.g. `micropython-20220618-v1.19.1`. But since 1.20 it's broken (same problem with 1.21).

It does work with ESP32, though. So I suspect it is a problem with the Pico emulation.

**Comment by urish** [comment]
Thanks for reporting! Can you please share a link to a demo project that demonstrates the issue?

**Comment by treysis** [comment]
Sure, see this for example:
https://wokwi.com/projects/381549021386487809

**Comment by urish** [comment]
Thanks, issue reproduced. Working on a solution.

**Comment by treysis** [comment]
For reference, here is a (generic?) ESP32 demo which works with 1.20+:
https://wokwi.com/projects/305568836183130690

**Comment by urish** [comment]
Thanks! Fix is up, can you please check?

**Comment by treysis** [comment]
Wow, that was lightning fast! Yes, it's working now. 👍 Thanks a lot!
