### ISSUE TITLE
ROR shift amount is 8 bits, not 5

### ISSUE THREAD

**Issue by PaulofPhx** [wokwi/rp2040js#14]
The ROR instruction masks the shift amount by 0xff rather than 0x1f.

This may or may not cause a problem depending on how the shift expression works in Typescript/Javascript.

**Comment by PaulofPhx** [comment]
I now don't believe this will be an issue with Javascript doing modulo 32 on the shifts.

I guess my background of using other languages, on other architectures (16, 32, and 64-bit), just makes be a bit skittish about leaving the implementation open.

You can close this issue if you want.

**Comment by urish** [comment]
Actually, adding modulo 32 sounds like a good idea, as it makes the code closer to the datasheet. Let's do it!
