### ISSUE TITLE
Implement Timer Alarms ⏰

### ISSUE THREAD

**Issue by urish** [wokwi/rp2040js#19]
They are described in section 4.6.3

**Comment by kilograham** [comment]
might be fun to try running pico_time_test from the SDK repo! Looking forward to being able to perhaps use rp2040js and the GDB client to implement some more off chip regression tests (and use as a test harness for on chip too!)

**Comment by kilograham** [comment]
... although actually it almost certainly needs spin locks to function correctly, so you can try it then!

**Comment by urish** [comment]
> might be fun to try running pico_time_test from the SDK repo!

Great idea, I'll try that!

> Looking forward to being able to perhaps use rp2040js and the GDB client to implement some more off chip regression tests

Anything I can do to help with this?

And on a different note - do you have any idea whether INTF wins over INTE? Or, in other words, whether:

1. `INTS = (INTR & INTE) | INTF`
\- or - 
2. `INTS = (INTR | INTF) & INTE`

**Comment by kilograham** [comment]
`INTS = (INTR & INTE) | INTF`

> Anything I can do to help with this?

Yeah, let's see if any of the 'tests' in the SDK pass first e.g. pico_time_test, pico_float_test, pico_divider_test (which actually check more things in the _develop_ branch). Although these last two will have to wait for the h/w divider :-) ... but the ability to easily run regression tests in giithub (better than using our "host" builds), and also use the same (possibly new) tests on silicon will be a big gain. So yeah, we may well reach out in the future!

**Comment by urish** [comment]
> `INTS = (INTR & INTE) | INTF`

And of course, we [got it the wrong way](https://github.com/wokwi/rp2040js/blob/9387184b9fd43595f68049f3ccdcdb1a5668d8a0/src/peripherals/timer.ts#L55). Glad I asked. Thanks!

> Yeah, let's see if any of the 'tests' in the SDK pass first e.g. pico_time_test, pico_float_test, pico_divider_test (which actually check more things in the develop branch).

Alright, we'll take a look at these as soon as we finish with the H/W divider (hopefully next Tuesday, but... who knows?)
