### ISSUE TITLE
hello_timer wrong printf output

### ISSUE THREAD

**Issue by Turro75** [wokwi/rp2040js#35]
running hello_timer.hex from pico examples result in this output:

> Unimplemented peripheral PADS_BANK0_BASE read from 4
> Unimplemented peripheral PADS_BANK0_BASE write to 4: -129
> Unimplemented peripheral IO_BANK0_BASE write to 4: 2
> Unimplemented peripheral PADS_BANK0_BASE read from 8
> Unimplemented peripheral PADS_BANK0_BASE read from 8
> Unimplemented peripheral PADS_BANK0_BASE write to 8: -129
> Unimplemented peripheral IO_BANK0_BASE write to c: 2
> UART sent:  H
> UART sent:  e
> UART sent:  l
> UART sent:  l
> UART sent:  o
> UART sent:   
> UART sent:  T
> UART sent:  i
> UART sent:  m
> UART sent:  e
> UART sent:  r
> UART sent:  !
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  T
> UART sent:  i
> UART sent:  m
> UART sent:  e
> UART sent:  r
> UART sent:   
> UART sent:  V
> UART sent:   
> UART sent:  f
> UART sent:  i
> UART sent:  r
> UART sent:  e
> UART sent:  d
> UART sent:  !
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> SEV
> UART sent:  c
> UART sent:  a
> UART sent:  n
> UART sent:  c
> UART sent:  e
> UART sent:  l
> UART sent:  l
> UART sent:  e
> UART sent:  d
> UART sent:  .
> UART sent:  .
> UART sent:  .
> UART sent:   
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> UART sent:  R
> UART sent:  e
> UART sent:  p
> UART sent:  e
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  a
> UART sent:  t
> UART sent:   
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> SEV
> UART sent:  c
> UART sent:  a
> UART sent:  n
> UART sent:  c
> UART sent:  e
> UART sent:  l
> UART sent:  l
> UART sent:  e
> UART sent:  d
> UART sent:  .
> UART sent:  .
> UART sent:  .
> UART sent:   
> UART sent:  V
> UART sent:  
> UART sent:  
> 
> SEV
> SEV
> UART sent:  D
> UART sent:  o
> UART sent:  n
> UART sent:  e
> UART sent:  
> UART sent:  
> 

while on a real pico it prints:                                                                
```
Hello Timer!                                              
Timer 1 fired!                                            
Repeat at 2501544                                         
Repeat at 3001630                                         
Repeat at 3501668
Repeat at 4001705
Repeat at 4501742
Timer 1 fired!
Repeat at 2503970
Repeat at 3004063                                                                   
Repeat at 3504105                                                                   
Repeat at 4004144                                                                   
Repeat at 4504182                                                                   
cancelled... 1                                                                      
Repeat at 7504054                                                                   
Repeat at 8004053                                                                   
Repeat at 8504053                                                                   
Repeat at 9004053                                                                   
Repeat at 9504053                                                                   
Repeat at 10004053                                                                  
cancelled... 1                                                                      
Done      
```                                                                          

Investigating with gdbdiff it looks like at some point the silicone runs code from bootrom and the emulator gets mad.
As far as I've seen it seems it does not properly handle the 16bit instructions when the memory address is in the bootrom memory.

on the silicone set a breakpoint at 0x10000416  (line 45 of hello_timer.c) then after roughly 70ish si it goes to bootrom memory area.

I tried this test, it actually use LSLS instruction instead of BL because not able to read/write properly at bootrom addresses:
```
it('should execute `bl 0x23c2` instruction', async () => {
    await cpu.setPC(0x00000122);
    await cpu.writeUint32(0x00000122, opcodeBL(0x23c2));
    await cpu.singleStep();
    const registers = await cpu.readRegisters();
    expect(registers.pc).toEqual(0x000024e8);
    expect(registers.lr).toEqual(0x00000127);
  });

```

**Comment by urish** [comment]
Hmm... so the emulator doesn't print the numbers correctly?

I suspect it may have to do with the integer divider that we still haven't implemented. 

Can you check if there are any writes to SIO addresses at 0xd0000060 or 0xd0000068 ?

**Comment by Turro75** [comment]
[out.txt](https://github.com/wokwi/rp2040js/files/6511777/out.txt)

correct, a lot of missing sio warnings, I didn't see anything to 68 but 60 there are, a lot.
also seen that __wrap_vprintf goes to bootrom

**Comment by urish** [comment]
Thanks for attaching the logs!

These are SIO reads (and not writes) but I can see some reads come from the integer divider area:

```
Read from invalid SIO address: 60
Read from invalid SIO address: 64
Read from invalid SIO address: 74
Read from invalid SIO address: 70
```

70 is DIV_QUOTIENT,  
74 is DIV_REMAINDER

I guess `printf()` is trying to divide the number by 10 each time to get one digit at a time, and it uses the integer divider for that. But we haven't implemented it yet, so it spits out garbage...

One workaround may be to disable the hardware divider. There's probably a way to tell them compiler not to use the hardware divider, I'll try to google that / look into the SDK sources

**Comment by urish** [comment]
I think this is the code is the build system which enables the hardware divider:

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_divider/CMakeLists.txt

So maybe adding 

```
pico_set_divider_implementation(hello_timer compiler)
```

to the project's CMakeLists.txt will do the trick?

**Comment by Turro75** [comment]
As it seemed not so complicated (for sure i introduced bugs, no doubt on this) I implemented the hardware divider and , as usual, You were right: the printf output is now correct

**Comment by urish** [comment]
You implemented the hardware divider? Cool! I'll check the pull request soon.
