### ISSUE TITLE
MOV wrong flags 

### ISSUE THREAD

**Issue by Turro75** [wokwi/rp2040js#48]
this is the test case:
Register	StartValue	Emulator	Silicone
r0  		0x22d0e560	0x22d0e560	0x22d0e560
pc  		0x10005332	0x10005334	0x10005334
xPSR* 		0x81000000	0x81000000	0x41000000
Flags		 [N---] 	 [N---] 	 [-Z--]

0x01005332:	00 00	movs	r0, r0

**Comment by urish** [comment]
Interesting, does this reproduce in a test case?

I see why the Negative flag should be cleared (`0x22d0e560` isn't negative), but have no idea why is the Zero flag set? this is obviously not zero

**Comment by Turro75** [comment]
indeed not able to replicate in test or silicone, hold on as it could be a gdbdiff bug.

**Comment by urish** [comment]
Ok, so I'm closing it for now. Thanks for reporting!
