### ISSUE TITLE
Possible error in MULS implementation

### ISSUE THREAD

**Issue by kilograham** [wokwi/rp2040js#5]
https://github.com/wokwi/rp2040js/blob/ce0359b81183becb6f347dcd8b7644db012db90e/src/rp2040.ts#L1080

I don't actually know TypeScript so may be wrong here (perhaps the multiplication is actually 32 bit), but given the existence of `Math.imul` I assume that is what you want instead as a `double` multiplication is going to going to lose precision in the lower 32 bits for larger inputs

**Comment by urish** [comment]
Good call Graham, thanks! 

Quick googling actually reveals [an example](https://stackoverflow.com/questions/11703599/unsigned-32-bit-integers-in-javascript) where you get bitten by the loss of precision:

```javascript
console.log((2654435769 * 340573321) | 0);      // 0
console.log(Math.imul(2654435769, 340573321));  // 1
```

We'll fix it in the [next live stream](https://youtu.be/7V5iaptW0ZA) on Tuesday. For references, these are the [docs for imul](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul).
