### ISSUE TITLE
ICSR (Interrupt Control and State Register) register is missing

### ISSUE THREAD

**Issue by kartben** [wokwi/rp2040js#94]
This is effectivley preventing the use of PENDSV interrupts, which are quite commonly used by Real-time operating systems

See [Interrupt Control and State Register
](https://developer.arm.com/documentation/dui0497/a/cortex-m0-peripherals/system-control-block/interrupt-control-and-state-register)

**Comment by urish** [comment]
Fixed & released as 0.14.9
